server:
  port: 9001
  servlet:
    context-path: /btmovie-provider

spring:
  application:
    name: btmovie-provider
  datasource:
    url: jdbc:mysql://localhost/BT_MOVIE
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapperLocations: classpath:mapping/*.xml
  typeAliasesPackage: com.zdran.springboot.domain

